import { useEffect } from "react";
import { ScrollView, StyleSheet, Text as RNText, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { SafeAreaView, type Edges } from "react-native-safe-area-context";
import { palette } from "@breeze/design-tokens";
import { Text } from "@/components/Text";
import { Button } from "@/components/Button";
import { AmbientGlow } from "@/components/AmbientGlow";
import { BOTTOM_NAV_RESERVED_HEIGHT } from "@/components/BottomNav";
import { useActivePauseStore } from "@/features/pause/use-active-pause-store";

/**
 * /pause/active/[id] — MOCK active-pause screen for M1 S10.
 *
 * Renders the activity payload generated by `generate-activity` Edge Function
 * (title + sub + motivation + emoji) so the end-to-end loop is observable.
 * The real timer + completion flow ships in M1 S11.
 *
 * Activity is read from `useActivePauseStore` (in-memory) because the pauses
 * table doesn't store `sub` yet. On cold reload (store empty) we fall back
 * to a minimal "pause #id" view — S11 will replace this with a real fetch.
 */
export default function ActivePauseScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const activity = useActivePauseStore((s) => s.activity);
  const clear = useActivePauseStore((s) => s.clear);

  // Clear the in-memory activity on unmount so a stale entry doesn't show
  // if the user re-enters another pause via a different id.
  useEffect(() => () => clear(), [clear]);

  const onVolver = () => {
    router.replace("/");
  };

  return (
    <SafeAreaView
      edges={["top"] as Edges}
      style={{ flex: 1, backgroundColor: palette.stone[50] }}
    >
      <AmbientGlow />
      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        {activity ? (
          <View style={styles.card}>
            <RNText style={styles.emoji}>{activity.emoji}</RNText>
            <View style={{ height: 12 }} />
            <Text variant="h1" weight="extrabold" color="text">
              {activity.title}
            </Text>
            <View style={{ height: 10 }} />
            <Text variant="body" color="text">
              {activity.sub}
            </Text>
            <View style={{ height: 22 }} />
            <Text variant="bodySm" color="muted">
              {activity.motivation}
            </Text>
            <View style={{ height: 8 }} />
            <Text variant="caption" color="muted">
              {activity.durationMinutes} min · pausa #{id?.slice(0, 8)}
            </Text>
          </View>
        ) : (
          <View style={styles.card}>
            <Text variant="h2" weight="bold" color="text">
              Pausa #{id?.slice(0, 8)}
            </Text>
            <View style={{ height: 8 }} />
            <Text variant="bodySm" color="muted">
              El timer y la pantalla completa de pausa activa llegan en M1 S11.
            </Text>
          </View>
        )}

        <View style={{ height: 28 }} />
        <Button variant="primary-pill" fullWidth onPress={onVolver}>
          Volver al inicio
        </Button>

        <View style={{ height: BOTTOM_NAV_RESERVED_HEIGHT }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  scroll: {
    paddingHorizontal: 20,
    paddingTop: 32,
  },
  card: {
    paddingVertical: 8,
  },
  emoji: {
    fontSize: 56,
    lineHeight: 64,
  },
});
